import Head from 'next/head'
import Image from 'next/image'
import { Center, Heading, VStack, HStack, Text, Button, ButtonGroup, Divider, Badge } from '@chakra-ui/react'
import { ArrowForwardIcon } from '@chakra-ui/icons'
import SupaIcon from '../public/supabase-logo-icon.png'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Center width='100vw' height='100vh'>
          <VStack spacing='24px' padding='10%'>
            <Heading size='3xl'>Embed github stars into your next app</Heading>
            <Text>Create visual feedback in your app, based on wether your github repo is starred.</Text>
            <Divider />
            <ButtonGroup>
              <Button size='lg' colorScheme='red' rightIcon={<ArrowForwardIcon />}>Sign up</Button>
              <Button size='lg'>Star on github</Button>
            </ButtonGroup>
            <HStack>
              <Image src={SupaIcon} width='15px' height='15px' />
              <Text paddingTop="2.5px">Signups powerd by supabase</Text>
            </HStack>
          </VStack>
        </Center>
        <Center width='100vw' height='100vh'>
          <HStack padding="10%">
            <VStack spacing="24px">
              <Heading>Star a repo right from your app</Heading>
              <Text>Deliver a frictionless starring experience, right from your app. Gone are the days of clicking more than once to star a repo ;).</Text>
            </VStack>
          </HStack>
        </Center>
      </main>
    </div>
  )
}
