import Head from 'next/head'
import Image from 'next/image'
import { Center, Heading, VStack, HStack, Text, Button, ButtonGroup, Divider, Input, Textarea } from '@chakra-ui/react'
import { ArrowForwardIcon } from '@chakra-ui/icons'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Center width='100vw' height='100vh'>
          <VStack spacing='24px' padding='10%'>
            <Heading size='xl'>Ready to go?</Heading>
            <Text>Here's how to get started.</Text>
            <Divider />
            <VStack>
                <Input placeholder="Github username" />
                <Input placeholder="Github repo name" />
                <Textarea placeholder="Here is a sample placeholder" backgroundColor="blackAlpha.800" resize="none" border="none" color="white" focusBorderColor="transparent" readOnly />
                <ButtonGroup>
                    <Button>Copy to clipboard</Button>
                </ButtonGroup>
            </VStack>
          </VStack>
        </Center>
      </main>
    </div>
  )
}
